// <auto-generated />
namespace BondIssuanceHackFest.DLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _110520194 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_110520194));
        
        string IMigrationMetadata.Id
        {
            get { return "201905110122148_11-05-2019-4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
